"""empty message

Revision ID: 4cc181daae87
Revises: 9ec0cf36051c
Create Date: 2022-09-25 14:09:14.256479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc181daae87'
down_revision = '9ec0cf36051c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'addresses', ['user'])
    op.create_unique_constraint(None, 'companies', ['user'])
    op.create_unique_constraint(None, 'geos', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'geos', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'addresses', type_='unique')
    # ### end Alembic commands ###
